restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 1
jobs: 30
keep-going: true
reason: true
printshellcmds: true
jobname: "{name}.{jobid}.snakejob.sh"
use-conda: true
conda-prefix: /mnt/beegfs/pipelines/rna-dge-salmon-deseq2/conda
use-singularity: true
singularity-prefix: /mnt/beegfs/pipelines/rna-dge-salmon-deseq2/singularity
wrapper-prefix: https://raw.githubusercontent.com/tdayris/snakemake-wrappers/Unofficial
